steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ar2-js:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ar2-js:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'ar2-js' # Change to your Cloud Run service name
  - '--image=gcr.io/$PROJECT_ID/ar2-js:$COMMIT_SHA'
  - '--platform=managed'
  - '--region=us-central1' # Replace with your desired region
  - '--allow-unauthenticated' # Remove this line if you want to require authentication

options:
  logging: CLOUD_LOGGING_ONLY
